[package]
name = "rss_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
feed-rs = "2.3.1"
notify = "8.1.0"
reqwest = "0.13.1"
sqlx = { version = "0.8", features = [
    "sqlite",
    "macros",
    "migrate",
    "runtime-tokio-native-tls",
] }


[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
strip = "symbols"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
debug-assertions = false
overflow-checks = false
